services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    volumes: [ ]
    environment:
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - 3307:3306
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
