ktor:
  development: true
  deployment:
    watch:
      - classes
      - resources
    port: 8080
  application:
    modules:
      - net.kigawa.fns.backend.ModulesKt.module

jwt:
  secret: ""
  issuer: "ISSUER"
  audience: "audience"
db:
  host: localhost:3006
  database: fns
  user: fns
  password: fns-pass
