/*
 * This file was generated by the Gradle 'init' task.
 */
import dependencies.ProjectConfig

plugins {
}

repositories {
  mavenLocal()
  maven {
    url = uri("https://repo.maven.apache.org/maven2/")
  }

  maven {
    url = uri("https://repo.papermc.io/repository/maven-public/")
  }

  maven {
    url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
  }

  maven {
    url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
  }
}

version = ProjectConfig.VERSION
group = ProjectConfig.GROUP
