ktor:
  development: true
  deployment:
    watch:
      - classes
      - resources
    port: 8080
  application:
    modules:
      - net.kigawa.fns.backend.ModulesKt.module

jwt:
  secret: ""
  issuer: ""
  audience: ""
  realm: ""