ktor:
  development: true
  deployment:
    watch:
      - classes
      - resources
    port: 8080
  application:
    modules:
      - net.kigawa.fns.backend.service.ModulesKt.loadModule

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASS}
