ktor:
  development: true
  deployment:
    watch:
      - classes
      - resources
    port: 8080
  application:
    modules:
      - net.kigawa.fns.backend.ModulesKt.loadModule

jwt:
  secret: ""
  issuer: "ISSUER"
  audience: "audience"
db:
  host: "localhost:3306"
  database: "fns"
  user: "fns"
  password: ""
